title: Antanas Murelis # your name (or website title) here
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Computational Biologist Master Student at ETH Zürich and Immunology Bachelor's degree from Trinity College Dublin. Generally interested in scientific computing, machine learning, and data science and their applications in Biology. 
  <br><br>
  <a href="https://www.linkedin.com/in/matt-chapman-ba8488118/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
